sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: QEhRepEBJyPgyKPHb7H+7fSBNA8sHZyXmlq1z3+nvHX2KfBrFs6tbQ8CwRO+xW/6B+KMypm4PVZqdwaR9gtmDNBgmsNjUVaKCrKwJd4wEX641tuWVEsr06qB+j1w9gyX0D1H1rNAge3ukQ/XQ1M67BcV0Edvs9aTdaNU7hDXzABqq9sCA9T9Beaj+7gPEK6IAL7wbLIIu7yzLTX0wS2sJKgvBBQX8g6ShKQWzgfn0FBgO6djQteplBgu3SjhA41GCYO6J/LuWp7UtFRHRW0oNoxoNOmmckLphDG3fioOHG38woj/bKxeV1+qeweIWyck6C08wLXa5JDxj6DmbvxCJMNR+pgkZDnx/IUE7OzPcXexck9AgvkmSEeeowW6umGUkUDZOK+hm4W3nkWrHQCVK4b0522gi5oysC/VzBd0+4Cuk5+UZAlgyfKgmt3j1gnRT/JMPn1995JxaT7eWDo0nQirots8V0GCsvTN35FxF4iMmXdI213F70TcFD+cr0KzHt9KoT4WrmLvpQ9MRG/mgYVJHa7Jmr2HVAQsghPZrvYM4e3P1PnbXIJY0aahEez0PMy/mgaGEcOrzlnNPkqI5buA/h+1wuRGuLKpiX3CEQZDL3BJYVSHmYG3pnnTAh7TjY9Bi5c+5ZChddtOcNtBw5mh3SdnjKBuVFbPoykX0e4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/A-Lute-of-Jade-Selections-from-the-Classical-Poets-of-China_390
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy